version: "3.7"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
  mongodb_container:
          image: mongo:latest
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
          ports:
            - 27018:27017